### PR TITLE
Rebrand configurator

### PR DESCRIPTION
**Pull request by kidBrazil**
Rebranded all assets of the configurator with ButterFlight. Changed the colors of the icons to match the Butterflight orange.

### CODE REVIEW

**Comment by hydra** [comment]
You should look at doing this using themes and folders like this:

https://github.com/cleanflight/cleanflight-configurator/tree/master/src/css

also, it's 100% confusing to everyone, developers especially, having BF and BF and BF.  (Baseflight, Betaflight, ButterFlight).

Can you work with the community to come up with a suitable abbreviation that isn't the same as existing ones?  This can then be used as prefixes to files, etc.  it would be most handy otherwise merging code and changes between the projects will be a serious issue.

**Comment by orneryd** [comment]
BaF BeF BuF!

**Comment by apocolipse** [comment]
Thanks @hydra :)  I think we've settled on BuF ;)

**Comment by hydra** [comment]
can i suggest BUFL for the 4 letter one?without going off-topic too much please be aware that you should change the firmware variant ASAP from BTFL to BUFL in the firmware code as it makes a mess of all the statistics that are collected in various apps, not limited to the configurator.  This is the reason it was added and made configurable!DominicOn 7 Mar 2018 01:34, Chris Simpson <notifications@github.com> wrote:Thanks @hydra :)  I think we've settled on BuF ;)

**Pull request merged**
