### PR TITLE
Point HELIO Hexes to their own repository

### PR DESCRIPTION
**Pull request by kidBrazil**
@orneryd added a fix to point the HELIO hexes to a new repository to keep the streams a little more separate.

### CODE REVIEW

**Comment by orneryd** [comment]
we will need to automate this in the future. but for now it will help prevent some confusion.

**Comment by kidBrazil** [comment]
we should probably increment version?

**Comment by orneryd** [comment]
Yes. we should increment the version.

**Comment by orneryd** [comment]
Just updated this to make it point to our repository for the releases.

**Pull request merged**
